#pragma once
// AYAnimation/BlendSpace.h — P2.1 (2026-07-27). Linear-simplex Blend Tree (UE BlendSpace
// / Unity AnimationBlendTree 1D/2D equivalent).
//
// Two independent classes — BlendSpace1D and BlendSpace2D — each holding
// N sample points, each sample backed by its own AnimationPlayer. On
// tick() the host advances every internal player; on evaluate() the
// BlendSpace samples per-bone weighted TRS into caller-provided buffers.
//
// Owned-player mode (canonical): each addSamplePoint() lazily constructs
// one AnimationPlayer bound to the supplied IAnimation. Lifetime is
// co-extensive with the BlendSpace. Works out of the box for hosts that
// don't want to manage per-clip state.
//
// Library mode: the static computeWeightedBoneTRS() helper accepts N
// already-evaluated per-clip out buffers + a weight vector. Hosts that
// already own per-clip AnimationPlayers (e.g. ECS systems that share
// per-clip players with an AnimationComponent slot) can plug into the
// math without owning internal players. Owned-player mode produces
// byte-identical output to library mode for identical inputs (test #11).
//
// Thread-safety: NOT thread-safe (mirrors AnimationPlayer's contract).
// The static computeWeightedBoneTRS helper is a pure function and may
// be invoked from any thread as long as the input vectors are not
// being mutated concurrently.
//
// Output semantics: evaluate() writes a "composite base pose" — the
// caller (BlendSpaceSystem or a custom renderer) is responsible for
// promoting per-bone local TRS to world/skin matrices. The composite
// is byte-compatible with the result AnimationPlayer produces when
// a single clip is bound; an Additive Layer pipeline can stack on top
// (orthogonal-fields model — see AYAnimationSystem.cpp memcpy pick).
//
// 2D simplex algorithm: linear search over an explicit Triangle list
// (preferred — set via setTriangulation()) OR the bounding-rect
// heuristic (default — works for ≤16 sample points, the production
// locomotion / hit-react range). Nearest-vertex fallback when no
// enclosing triangle is found. See BlendSpace.cpp::rebuildWeights().

#include <AYAnimation/AnimationPlayer.h>

#include <AYMath/MathTypes.h>

#include <AYResource/assetsDefs/IAnimation.h>

#include <cstdint>
#include <memory>
#include <vector>

namespace ayt::anim
{

// P2.1 — single triangle in 2D sample space. Indices refer to the
// BlendSpace2D's _samples array. Provided by the editor at author time
// (set via setTriangulation()) for ≥3 sample points, OR generated by
// the bounding-rect heuristic when none is supplied.
struct Triangle {
    uint32_t a = 0;
    uint32_t b = 0;
    uint32_t c = 0;
};

// ===========================================================================
// BlendSpace1D — linear interpolation between the two nearest sample
// points on a 1D parameter axis. Single-active-vertex fast path when
// the parameter is outside the bracketing range.
// ===========================================================================
class BlendSpace1D {
public:
    struct SamplePoint {
        float                                          parameter = 0.0f;
        std::shared_ptr<const ayt::resource::IAnimation> clip;
    };

    // Authoring API ─────────────────────────────────────────────────
    // Append a new sample point. clip may be nullptr for the duration
    // of an authoring session — setSkeleton() rebinds the player. On
    // rebuildWeights() this point is sorted into the parameter axis.
    void addSamplePoint(float parameter,
                        std::shared_ptr<const ayt::resource::IAnimation> clip);

    // Drop every sample point and free the internal players.
    void removeAllSamplePoints();

    size_t getSamplePointCount() const { return _samples.size(); }
    size_t getActiveVertexCount() const { return _activeIndices.size(); }
    const std::vector<size_t>& getActiveIndices() const { return _activeIndices; }
    const std::vector<float>&  getActiveWeights() const { return _activeWeights; }

    // Skeleton binding ──────────────────────────────────────────────
    // P1.7 contract: shared_ptr to a shared ISkeleton asset. N
    // BlendSpaces bound to the same asset pin its lifetime and share
    // AssetBoneCache entries for bone-name resolution.
    void setSkeleton(std::shared_ptr<const ayt::resource::ISkeleton> skel);

    // Parameter input ───────────────────────────────────────────────
    // Recomputes the active simplex (1 or 2 sample points). Call once
    // per frame, BEFORE tick(). setParameter() does NOT advance time
    // — it only updates which sample points are "near" the input.
    void setParameter(float p);
    float getParameter() const { return _parameter; }

    // Per-frame driver ──────────────────────────────────────────────
    // tick(dt) advances every internal AnimationPlayer's time axis
    // by dt * playRate. Uniform forward rate (UE/Unity convention);
    // callers can later override per-sample playRate if needed (P2.x).
    // Call after setParameter(), before evaluate().
    void tick(float dt);

    // Composite output ──────────────────────────────────────────────
    // Writes n * 3 / n * 4 / n * 3 floats into the out-arrays, where
    // n = skeleton bone count. Caller must have invoked
    // resizeTRS(n) once after setSkeleton(). evaluate() does NOT
    // clear the buffers; it OVERWRITES every element. Missing tracks
    // (sample has no track for bone k) fall back to the skeleton's
    // rest-pose local TRS for that bone — identical to
    // AnimationPlayer Phase 1a semantics.
    void evaluate(std::vector<float>& outLocalPos,
                  std::vector<float>& outLocalRot,
                  std::vector<float>& outLocalScl);

    // Allocate / deallocate the out-arrays to match n bones. Call once
    // after setSkeleton() and whenever the skeleton bone count
    // changes. Idempotent.
    void resizeTRS(size_t n);
    size_t getTRSLength() const { return _skelBoneCount; }

    // Playback controls ─────────────────────────────────────────────
    void setPlayRate(float r) { _playRate = r; }
    float getPlayRate() const  { return _playRate; }
    void setLoop(bool loop)    { _loop = loop; }
    bool  getLoop() const      { return _loop; }

    // Library mode ─────────────────────────────────────────────────
    // Pure helper: takes N per-clip local-TRS buffers (already filled
    // by caller-side AnimationPlayer::evaluate()) and writes a
    // per-bone weighted sum into the out-arrays. Mirrors owned-player
    // mode output bit-for-bit. weights.size() must equal
    // srcLocalPos.size(); out arrays sized to n * stride.
    //
    // Position math:  resultPos[k] = Σ_i w[i] * srcPos[i][k]
    // Rotation math:  for each active i:
    //                   delta[i] = srcRot[i][k] * bindRot.inverse()
    //                   accum   *= delta[i].pow(w[i])
    //                 resultRot[k] = (accum * bindRot).normalize()
    // Scale math:     resultScl[k] = Σ_i (w[i] * srcScl[i][k]) on each axis
    //
    // skel is used to read the bind-pose local TRS; pass the same
    // shared_ptr that was bound to the AnimationPlayers driving
    // srcLocal*. nullptr skel is an error (assert in debug).
    static void computeWeightedBoneTRS(
        const std::vector<std::vector<float>>& srcLocalPos,
        const std::vector<std::vector<float>>& srcLocalRot,
        const std::vector<std::vector<float>>& srcLocalScl,
        const std::vector<float>&              weights,
        const ayt::resource::ISkeleton*        skel,
        std::vector<float>&                    outLocalPos,
        std::vector<float>&                    outLocalRot,
        std::vector<float>&                    outLocalScl);

private:
    // Internal helpers — defined in BlendSpace.cpp.
    void ensurePlayer(size_t sampleIndex);
    void rebuildWeights();

    // Per-sample authoring data.
    std::vector<SamplePoint>                        _samples;
    std::vector<std::unique_ptr<AnimationPlayer>>   _players;

    // Skeleton binding (P1.7 shared_ptr model).
    std::shared_ptr<const ayt::resource::ISkeleton> _skeleton;

    // Sample input and playback config.
    float _parameter = 0.0f;
    float _playRate  = 1.0f;
    bool  _loop      = true;

    // Cached active simplex — recomputed in setParameter() / rebuildWeights().
    // _activeIndices holds the sample indices whose weight > 0 (≤2 for 1D);
    // _activeWeights is the matching normalized weight vector (sum == 1).
    std::vector<size_t> _activeIndices;
    std::vector<float>  _activeWeights;

    // Lazy sized by resizeTRS().
    size_t _skelBoneCount = 0;
};

// ===========================================================================
// BlendSpace2D — barycentric blending across the triangle containing the
// parameter point (≤3 active sample points). Same API shape as
// BlendSpace1D; differs only in sample-axis dimensionality, simplex
// algorithm (Triangle search vs sorted-pair), and bounding-rect fallback.
// ===========================================================================
class BlendSpace2D {
public:
    struct SamplePoint {
        ayt::math::FVector2                           position;
        std::shared_ptr<const ayt::resource::IAnimation> clip;
    };

    void addSamplePoint(ayt::math::FVector2 position,
                        std::shared_ptr<const ayt::resource::IAnimation> clip);

    void removeAllSamplePoints();

    size_t getSamplePointCount() const { return _samples.size(); }
    size_t getActiveVertexCount() const { return _activeIndices.size(); }
    const std::vector<size_t>& getActiveIndices() const { return _activeIndices; }
    const std::vector<float>&  getActiveWeights() const { return _activeWeights; }

    void setSkeleton(std::shared_ptr<const ayt::resource::ISkeleton> skel);

    void setParameter(ayt::math::FVector2 p);
    ayt::math::FVector2 getParameter() const { return _parameter; }

    void tick(float dt);

    void evaluate(std::vector<float>& outLocalPos,
                  std::vector<float>& outLocalRot,
                  std::vector<float>& outLocalScl);

    void resizeTRS(size_t n);
    size_t getTRSLength() const { return _skelBoneCount; }

    // Editor-supplied triangulation. Pass a vector of Triangle{a,b,c}
    // where each index is into _samples (added via addSamplePoint).
    // Once supplied, the runtime uses ONLY these triangles — the
    // bounding-rect heuristic is bypassed. Pass an empty vector to
    // revert to the heuristic.
    //
    // Production authoring tool should precompute Delaunay once at
    // edit time and ship the result via this API. Runtime fallback
    // (no triangles + ≥3 samples) → bounding-rect heuristic; if that
    // also fails → nearest vertex.
    void setTriangulation(const std::vector<Triangle>& triangles);
    const std::vector<Triangle>& getTriangulation() const { return _triangles; }

    void setPlayRate(float r) { _playRate = r; }
    float getPlayRate() const  { return _playRate; }
    void setLoop(bool loop)    { _loop = loop; }
    bool  getLoop() const      { return _loop; }

    // Library mode — same signature as BlendSpace1D but the weights
    // vector is up to 3 entries instead of 2.
    static void computeWeightedBoneTRS(
        const std::vector<std::vector<float>>& srcLocalPos,
        const std::vector<std::vector<float>>& srcLocalRot,
        const std::vector<std::vector<float>>& srcLocalScl,
        const std::vector<float>&              weights,
        const ayt::resource::ISkeleton*        skel,
        std::vector<float>&                    outLocalPos,
        std::vector<float>&                    outLocalRot,
        std::vector<float>&                    outLocalScl);

private:
    void ensurePlayer(size_t sampleIndex);
    void rebuildWeights();

    // Returns true + fills (u, v, w) such that p == u*A + v*B + w*C and
    // u+v+w == 1 when p lies inside the triangle. False when p is
    // strictly outside. Boundary points (signed distance 0) return true.
    static bool barycentric2D(const ayt::math::FVector2& p,
                              const ayt::math::FVector2& a,
                              const ayt::math::FVector2& b,
                              const ayt::math::FVector2& c,
                              float& u, float& v, float& w);

    // Build the bounding-rect heuristic triangulation for the current
    // sample set (called from rebuildWeights() when _triangles is empty).
    // For ≤16 sample points this produces a coarse rectangle with two
    // triangles per non-overlapping pair — sufficient for production
    // locomotion / hit-react spaces. Larger sets should precompute via
    // setTriangulation() instead.
    void buildHeuristicTriangulation();

    std::vector<SamplePoint>                        _samples;
    std::vector<std::unique_ptr<AnimationPlayer>>   _players;
    std::shared_ptr<const ayt::resource::ISkeleton> _skeleton;

    ayt::math::FVector2 _parameter{0.0f, 0.0f};
    float               _playRate = 1.0f;
    bool                _loop     = true;

    std::vector<size_t>    _activeIndices;   // ≤3 for 2D
    std::vector<float>     _activeWeights;
    std::vector<Triangle>  _triangles;       // empty → heuristic at first call

    size_t _skelBoneCount = 0;
};

} // namespace ayt::anim